### ISSUE TITLE
Tutorial課題 - chris

### ISSUE THREAD

**Issue by DaikiKash** [snowfly627/festinaLente-for-gudhagudhaLife#4]
Tutorial課題#3 を実施してみてね。

**Comment by DaikiKash** [comment]
- ブラウザのコンソールに`Resource interpreted as Stylesheet but transferred with MIME type text/plain`の警告文が出るけどなんで？
 - `kudou/`フォルダ別に切らなくてよくて、拡張していくように書いて欲しい（後々の人が競合解決の練習になるし）
 - 階層変じゃない？
   ```
   html/css/hoge.css
   html/fuga.html
   ```
   html配下にcssを入れる理由は？

**Comment by chris949** [comment]
＞ブラウザのコンソールにResource interpreted as Stylesheet but transferred with MIME type text/plainの
＞警告文が出るけどなんで？
ブラウザのコンソールは確認してなかった。確認します。

＞kudou/フォルダ別に切らなくてよくて、拡張していくように書いて欲しい
＞（後々の人が競合解決の練習になるし）
了解っす。おんなじファイルをガンガン編集していく感じでいいのかな？

＞階層変じゃない？
＞html/css/hoge.css
＞html/fuga.html
＞html配下にcssを入れる理由は？
htmlディレクトリと同じ階層に入れるのがいいのはわかってるんだけど、なぜかmimeが認識してくれなくて。。。調べてみまーす。

**Comment by DaikiKash** [comment]
同じファイルガンガン編集して良いぜ！
俺のイメージではこんな感じ
```
views/html/a.html
         /css/b.css
```
viewsフォルダでユーザへのブラウザ展開用ってまとまりになってるからね

**Comment by chris949** [comment]
issueに紐づけてcommitすんの忘れてた。。。
ざっとコメントしてくれた点は修正しました。
警告文はHTTPヘッダに書き込む"Content-Type"が"Conten-Type"になってたのが原因だった！

**Comment by DaikiKash** [comment]
ヘェ〜、Content-Typeの綴り間違っても読み込んでくれるのかぁ。

- main.htmlの`<h2>`が`</h1>`で閉じられている
  ```
   <body>
	    <h2>MainPage</h1>
	    <p>tutorialで作成したWEBページのメイン画面です。</p>
  ```
- postリクエスト処理が記載されてない
- html側でjs読み込んでhtml側（ユーザブラウザ側）でのjs処理が記載されてない

やっとチュートリアル課題半分ってとこかなぁ〜
頑張れーー

因みにcssフォルダにわざわざREADME.mdは載せなくても良いぜ。（まぁあれば嬉しいけども...）

**Comment by chris949** [comment]
期限も近づいてきたんで取り急ぎjs処理を実装。
jsによるタブ操作は下記サイトを参照
https://www.webdlab.com/labs/dropdownmenu-2/

**Comment by DaikiKash** [comment]
課題完了を確認したのでクローズ。
